### ISSUE TITLE
can't use minified library standalone

### ISSUE THREAD

**Issue by themadcreator** [pboyer/verb#15]
I downloaded the minified javascript directly from the site at this url:
http://verbnurbs.com/js/verb.min.js

But, when i require in this library in node, I get a stack like:
```
Error: Cannot find module 'numeric'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/bdwyer/git/vecdraw/lib/verb.js:2:258)
```

Also, AFAICT, 'numeric' isn't listed as a dependency in package.json

**Comment by pboyer** [comment]
Sorry for the late reply on this. numeric is no longer a dependency in 2.0.0. I'll be updating this source very soon.
